# ============================================================
# PHASE 5: TOPIC MODELING WITH LDA
# File: phase5_topic_modeling.py
#
# What this file does:
#   - Converts article text into TF-IDF vectors
#   - Runs LDA (Latent Dirichlet Allocation) to discover hidden topics
#   - Assigns each article to its dominant topic
#   - Generates a word cloud for visualization
#   - Saves topic assignments for the dashboard
#
# WHAT IS TOPIC MODELING?
#   Imagine you have 500 news articles and NO labels.
#   Topic modeling AUTOMATICALLY discovers that:
#       Topic 1 is about → inflation, CPI, prices, consumer, fed
#       Topic 2 is about → earnings, revenue, profit, quarterly, shares
#       Topic 3 is about → recession, GDP, growth, unemployment, jobs
#   It does this by finding groups of words that tend to appear together.
#
# LDA INTUITION:
#   Each document = a MIX of topics (e.g., 70% inflation, 30% stocks)
#   Each topic = a distribution over ALL words in the vocabulary
#   LDA finds the topic distributions that best explain all documents.
# ============================================================

import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.decomposition import LatentDirichletAllocation
from wordcloud import WordCloud
import matplotlib.pyplot as plt
import os


# ─────────────────────────────────────────
# CONFIGURATION
# ─────────────────────────────────────────

INPUT_FILE  = "data/articles_ner.csv"        # Output from Phase 4
OUTPUT_FILE = "data/articles_topics.csv"     # Final complete dataset

N_TOPICS = 5          # Number of topics to discover (tune this)
N_TOP_WORDS = 10      # Number of top words to show per topic
RANDOM_STATE = 42     # For reproducibility (same results every run)


# ─────────────────────────────────────────
# STEP 1: TF-IDF Vectorization
# ─────────────────────────────────────────

def build_tfidf_matrix(texts: pd.Series):
    """
    Converts a collection of text documents into a TF-IDF matrix.

    WHAT IS TF-IDF?
    TF-IDF = Term Frequency × Inverse Document Frequency

    Term Frequency (TF):
        How often does a word appear in THIS document?
        "inflation" appears 5 times in an article → high TF

    Inverse Document Frequency (IDF):
        How RARE is this word across ALL documents?
        "inflation" appears in 400/500 articles → low IDF (common = less info)
        "stagflation" appears in 5/500 articles → high IDF (rare = more info)

    TF-IDF Score = TF × IDF
        High score → word is frequent in this doc BUT rare across all docs
        This identifies the words that CHARACTERIZE each document

    Parameters:
        texts : Series of preprocessed text strings

    Returns:
        tfidf_matrix  : Sparse matrix (n_docs × n_words)
        vectorizer    : Fitted TfidfVectorizer (to decode word indices later)
    """
    print("📐 Building TF-IDF matrix...")

    vectorizer = TfidfVectorizer(
        max_features=5000,      # Keep only top 5000 most informative words
        max_df=0.90,            # Ignore words appearing in >90% of docs (too common)
        min_df=3,               # Ignore words appearing in <3 docs (too rare / noise)
        ngram_range=(1, 2),     # Use single words AND 2-word phrases ("interest rate")
        sublinear_tf=True       # Apply log(TF) to dampen the effect of very frequent words
    )

    # fit_transform: learns the vocabulary from all texts, then converts to matrix
    tfidf_matrix = vectorizer.fit_transform(texts)

    vocab_size = len(vectorizer.get_feature_names_out())
    print(f"✅ TF-IDF matrix built: {tfidf_matrix.shape[0]} docs × {vocab_size} terms\n")

    return tfidf_matrix, vectorizer


# ─────────────────────────────────────────
# STEP 2: Build Count Vectorizer for LDA
# ─────────────────────────────────────────

def build_count_matrix(texts: pd.Series):
    """
    Builds a raw word count matrix for LDA.

    LDA uses RAW COUNTS (not TF-IDF) because it's a probabilistic model
    that assumes documents are generated by randomly sampling words from
    topic distributions. Counts fit this generative assumption better.
    TF-IDF weights don't align with LDA's probability framework.

    Parameters:
        texts : Series of preprocessed text strings

    Returns:
        count_matrix  : Sparse count matrix
        count_vectorizer : Fitted CountVectorizer
    """
    print("📐 Building Count matrix for LDA...")

    count_vectorizer = CountVectorizer(
        max_features=3000,
        max_df=0.90,
        min_df=3,
        ngram_range=(1, 2)
    )

    count_matrix = count_vectorizer.fit_transform(texts)
    print(f"✅ Count matrix built: {count_matrix.shape}\n")

    return count_matrix, count_vectorizer


# ─────────────────────────────────────────
# STEP 3: Train LDA Model
# ─────────────────────────────────────────

def train_lda(count_matrix, n_topics: int = 5):
    """
    Trains the LDA (Latent Dirichlet Allocation) topic model.

    HOW LDA WORKS (step by step):
    1. INITIALIZATION: Randomly assign every word in every document to a topic
    2. ITERATION (Gibbs Sampling):
       For each word in each document:
         → Look at what topic it's currently assigned to
         → Look at what topics other words in the SAME DOCUMENT use
         → Look at what topics use this word in OTHER DOCUMENTS
         → Reassign this word to the most likely topic given these two signals
    3. CONVERGENCE: After many iterations, topic assignments stabilize
    4. OUTPUT:
       → Topic-word matrix: probability of each word given each topic
       → Document-topic matrix: mixture weights of topics in each document

    KEY HYPERPARAMETERS:
        n_components (n_topics): How many topics to find
        doc_topic_prior (alpha): How mixed topics can be per document
                                 Low alpha → each doc focuses on few topics
        topic_word_prior (beta): How spread out each topic's words are
                                 Low beta → each topic focuses on few words

    Parameters:
        count_matrix : Word count matrix from CountVectorizer
        n_topics     : Number of topics to discover

    Returns:
        Trained LDA model
    """
    print(f"🧠 Training LDA with {n_topics} topics...")
    print("   (This uses Variational Bayes inference — may take 1-2 minutes)\n")

    lda = LatentDirichletAllocation(
        n_components=n_topics,      # Number of topics
        doc_topic_prior=0.1,        # Low alpha → documents focus on fewer topics
        topic_word_prior=0.01,      # Low beta → topics are more specific
        learning_method='batch',    # Use full dataset each iteration (better quality)
        max_iter=20,                # Number of EM iterations
        random_state=RANDOM_STATE,
        n_jobs=-1                   # Use all CPU cores
    )

    lda.fit(count_matrix)

    # Perplexity: measures how surprised the model is by new documents
    # Lower perplexity = better model (it's more "certain" about topics)
    perplexity = lda.perplexity(count_matrix)
    print(f"✅ LDA trained! Model perplexity: {perplexity:.1f}")
    print("   (Lower perplexity = better topic separation)\n")

    return lda


# ─────────────────────────────────────────
# STEP 4: Display discovered topics
# ─────────────────────────────────────────

def display_topics(lda_model, count_vectorizer, n_top_words: int = 10) -> dict:
    """
    Extracts and displays the top words for each discovered topic.

    Each LDA topic is a probability distribution over ALL words.
    The top words = words with the highest probability for that topic.
    We use these to INTERPRET what each topic is "about".

    Parameters:
        lda_model        : Trained LDA model
        count_vectorizer : Fitted CountVectorizer (gives us word names)
        n_top_words      : How many top words to show per topic

    Returns:
        Dictionary of {topic_number: [word1, word2, ...]}
    """
    feature_names = count_vectorizer.get_feature_names_out()

    # lda_model.components_ is the topic-word matrix
    # Shape: (n_topics, n_words)
    # Each row = one topic; values = word probabilities (unnormalized)

    topics = {}

    print("─" * 60)
    print("🗂️  DISCOVERED TOPICS:")
    print("─" * 60)

    for topic_idx, topic_word_weights in enumerate(lda_model.components_):
        # argsort gives indices that WOULD sort the array ascending
        # [-n:] takes the last n (highest values)
        # [::-1] reverses to get descending order
        top_word_indices = topic_word_weights.argsort()[-n_top_words:][::-1]
        top_words = [feature_names[i] for i in top_word_indices]

        topics[topic_idx] = top_words

        print(f"\n📌 Topic {topic_idx + 1}:")
        print(f"   {' | '.join(top_words)}")

    print("─" * 60)
    return topics


# ─────────────────────────────────────────
# STEP 5: Assign topics to documents
# ─────────────────────────────────────────

def assign_topics_to_documents(df: pd.DataFrame, lda_model, count_matrix) -> pd.DataFrame:
    """
    Assigns each article to its DOMINANT topic.

    lda_model.transform() returns the document-topic matrix:
    Each row = one document
    Each column = probability of that topic in that document

    Example for one document:
    [0.05, 0.72, 0.08, 0.10, 0.05]
    → Topic 2 dominates (72% of this document's words come from Topic 2)

    Parameters:
        df           : Main articles DataFrame
        lda_model    : Trained LDA model
        count_matrix : Word count matrix

    Returns:
        DataFrame with 'dominant_topic' and 'topic_probability' columns
    """
    print("\n🔀 Assigning topics to documents...")

    # Get document-topic matrix (probabilities)
    doc_topic_matrix = lda_model.transform(count_matrix)
    # Shape: (n_documents, n_topics)

    # Dominant topic = column with highest probability
    df['dominant_topic'] = doc_topic_matrix.argmax(axis=1) + 1  # +1 for human-readable (1-indexed)

    # Confidence = probability of the dominant topic
    df['topic_probability'] = doc_topic_matrix.max(axis=1).round(4)

    print(f"✅ Topic assignment complete!\n")
    print("Topic distribution across articles:")
    print(df['dominant_topic'].value_counts().sort_index().to_string())
    print()

    return df


# ─────────────────────────────────────────
# STEP 6: Generate Word Clouds
# ─────────────────────────────────────────

def generate_wordclouds(df: pd.DataFrame, n_topics: int):
    """
    Generates one word cloud per topic.

    A word cloud visualizes word frequency — more frequent words
    appear larger. Each topic's cloud shows the most common words
    in articles dominated by that topic.

    Saves PNG files to the 'visualizations/' folder.

    Parameters:
        df       : DataFrame with 'processed_text' and 'dominant_topic'
        n_topics : Number of topics
    """
    print("☁️  Generating word clouds for each topic...")
    os.makedirs("visualizations", exist_ok=True)

    fig, axes = plt.subplots(1, n_topics, figsize=(6 * n_topics, 4))

    for topic_num in range(1, n_topics + 1):
        # Get all articles assigned to this topic
        topic_articles = df[df['dominant_topic'] == topic_num]['processed_text']

        if len(topic_articles) == 0:
            continue

        # Combine all text for this topic into one big string
        combined_text = " ".join(topic_articles.dropna().tolist())

        # Generate word cloud
        wordcloud = WordCloud(
            width=800,
            height=400,
            background_color='white',
            max_words=50,
            colormap='Blues',           # Color scheme — try 'Reds', 'Greens' etc.
            collocations=False          # Don't repeat phrases
        ).generate(combined_text)

        # Display in subplot
        ax = axes[topic_num - 1] if n_topics > 1 else axes
        ax.imshow(wordcloud, interpolation='bilinear')
        ax.set_title(f"Topic {topic_num}", fontsize=14, fontweight='bold')
        ax.axis('off')

        # Also save individual PNG
        wordcloud.to_file(f"visualizations/topic_{topic_num}_wordcloud.png")
        print(f"  ✅ Saved word cloud for Topic {topic_num}")

    plt.tight_layout()
    plt.savefig("visualizations/all_topics_wordcloud.png", dpi=150)
    print("\n✅ All word clouds saved to 'visualizations/' folder\n")


# ─────────────────────────────────────────
# MAIN — Run everything in order
# ─────────────────────────────────────────

def main():
    print("=" * 55)
    print("  🗂️  PHASE 5: Topic Modeling")
    print("=" * 55)

    # Load from Phase 4
    print(f"\n📂 Loading from '{INPUT_FILE}'...")
    df = pd.read_csv(INPUT_FILE)

    # Drop rows with empty processed text (can't do topic modeling on empty strings)
    df = df.dropna(subset=['processed_text'])
    df = df[df['processed_text'].str.strip() != '']
    print(f"✅ Loaded {len(df)} articles with valid text\n")

    # Step 1: TF-IDF (for keyword analysis later)
    tfidf_matrix, tfidf_vectorizer = build_tfidf_matrix(df['processed_text'])

    # Step 2: Count matrix (for LDA)
    count_matrix, count_vectorizer = build_count_matrix(df['processed_text'])

    # Step 3: Train LDA
    lda_model = train_lda(count_matrix, n_topics=N_TOPICS)

    # Step 4: Show discovered topics
    topics = display_topics(lda_model, count_vectorizer, n_top_words=N_TOP_WORDS)

    # Step 5: Assign topics to articles
    df = assign_topics_to_documents(df, lda_model, count_matrix)

    # Step 6: Generate word clouds
    generate_wordclouds(df, n_topics=N_TOPICS)

    # Save final complete dataset
    df.to_csv(OUTPUT_FILE, index=False)
    print(f"💾 Saved complete dataset to '{OUTPUT_FILE}'")

    print("\n✅ Phase 5 Complete!")
    print("🎉 All 5 phases done! Now run: streamlit run dashboard.py")


if __name__ == "__main__":
    main()
